# User config
author: "Rafael Della Coletta, Ph.D. candidate at University of Minnesota"
tagline: "about me"
description: "Driven computational biologist focused on delivering improved and resilient crops to maintain food supply and progress towards healthier societies and ecosystems."
email: "della028@umn.edu"
linkedin: "https://www.linkedin.com/in/rafael-della-coletta/"
twitter: "https://twitter.com/rafael_coletta"
github: "https://github.com/rdcoletta"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
